name: DJHOWARDHOPE
favicon: null
layout_spectrum: 0.9297872
typography_spectrum: 0.2978723
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: DJ HOWARD HOPE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#30171F'
    - '#39425C'
    - '#6588B4'
    - '#885C43'
    - '#BEB5BC'
  brandStrength: 0.4650004373397678
  lightness: 0.2595745
  saturation: 0.6744681
  rhythmicContrast: 0.4679504
purpose: []
